x=input('Enter your Name')
print(x)
y=input('Enter a number')
print(y)
z=int(y)
w=input('Enter a floating number')
print(w)
v=float(w)
u=input('Enter a complex number')
print(u)
t=complex(u)
print(type(x),type(y),type(z),type(v),type(t))
